# Use a base image with Node.js installed
FROM node:18.14.0-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy the frontend source code to the container
COPY . .

# Install dependencies and build the frontend application
RUN npm ci && npm run build

# Create a new image with the compiled application
FROM nginx:alpine

# Copy your custom NGINX configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built frontend files to the NGINX server
COPY --from=build /app/dist/flallery-angular /usr/share/nginx/html

# Expose the port on which the frontend application will run
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
