version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=flallery
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5433:5432"

  client:
    container_name: client
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"

  backend:
    container_name: backend
    build: ./ # Path to your Spring backend Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flallery
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin1234

  frontend:
    container_name: frontend
    build: ../flallery-angular  # Path to your Angular frontend Dockerfile
    restart: always
    ports:
      - "4200:4200"
    environment:
      - API_BASE_URL=http://localhost:8080
